---

- name: Enable NetworkManager
  ansible.builtin.command: arch-chroot /mnt systemctl enable NetworkManager

- name: Enable reflector
  ansible.builtin.command: arch-chroot /mnt systemctl enable reflector
