---

- name: Replace the HOOKS with needed boot hooks in mkinitcpio.conf
  ansible.builtin.lineinfile:
    regexp: "^HOOKS="
    line: "HOOKS=(base udev autodetect modconf kms keyboard keymap consolefont block encrypt lvm2 filesystems fsck)"
    path: /mnt/etc/mkinitcpio.conf

- name: Run mkinitcpio -P
  ansible.builtin.command: arch-chroot /mnt mkinitcpio -P
