---

- name: Set /etc/hostname
  ansible.builtin.template:
    src: hostname.j2
    dest: /mnt/etc/hostname
    mode: '0644'
    owner: root
    group: root

- name: Set /etc/hosts
  ansible.builtin.template:
    src: hosts.j2
    dest: /mnt/etc/hosts
    mode: '0644'
    owner: root
    group: root
