---

- name: Install a user environment
  hosts: all
  roles:
    - { role: create_users }
    - { role: create_dirs }
    - { role: reflector }
    - { role: repos }
    - { role: package_install }
    - { role: stow }
