# the IP address of your target. use 'localhost' if you're running this on the tdt archiso
ansible_host:
# pick a suitable ansible user, later to become the admin user
ansible_user:
ansible_become_pass: "{{ become_pass }}" # contained in the vault
# pick a hostname
hostname:

# add lines to this list if you want "fake" DNS resolution
hosts_ips: |
  127.0.0.1 localhost
  127.0.1.1 localhost
  ::1       localhost
  ff02::1   ip6-allnodes
  ff02::2   ip6-allrouters
