---

- name: Remove conflict files
  ansible.builtin.file:
    path: "{{ user_conflicts }}"
    state: absent
  loop:
    - "/home/{{ admin_user }}/.bashrc"
    - "/home/{{ admin_user }}/.bash_profile"
  loop_control:
    loop_var: user_conflicts

- name: Remove root conflict files
  ansible.builtin.file:
    path: "{{ root_conflicts }}"
    state: absent
  loop:
    - /etc/pulse/default.pa
    - /etc/pulse/system.pa
    - /etc/tlp.conf
  loop_control:
    loop_var: root_conflicts
  become: true

# TODO: make this a loop
- name: Stow {{ admin_user }} user files
  ansible.builtin.shell: stow -vt ~ {cmus,dmenu,dunst,homeDirFiles,i3,newsboat,nvim,picom,ranger,redshift,ssh,st,texmf,user-dirs,userSystemD,vim}
  args:
    chdir: /usr/local/etc/user_configs/

- name: Stow root files
  ansible.builtin.command: stow -vt / rootItems
  args:
    chdir: /usr/local/etc/user_configs/
  become: true

- name: Set perms on rootItems
  ansible.builtin.file:
    path: /usr/local/etc/user_configs/rootItems
    owner: root
    group: root
    recurse: true
  become: true

- name: Set nvim to vi
  ansible.builtin.file:
    src: /usr/bin/nvim
    dest: /usr/bin/vi
    state: link
  become: true

- name: Set root vimrc to use our config
  ansible.builtin.lineinfile:
    insertafter: eof
    line: source /usr/local/etc/user_configs/vim/.config/vim/vimrc
    path: /etc/vimrc
  become: true

- name: Make suckless st
  ansible.builtin.script: /usr/local/etc/scripts/stMake
  become: true

- name: Make suckless dmenu
  ansible.builtin.script: /usr/local/etc/scripts/dmenuMake
  become: true
