---

- name: Set hwclock
  ansible.builtin.command: "arch-chroot /mnt hwclock --systohc"
  register: set_hwclock
  changed_when: set_hwclock.rc > 0

- name: Set timezone
  ansible.builtin.file:
    state: link
    src: "/usr/share/zoneinfo/{{ timezone }}"
    dest: "/mnt/etc/localtime"

- name: Set locale.gen
  ansible.builtin.template:
    src: locale.gen
    dest: /mnt/etc/locale.gen
    mode: '0644'
    owner: root
    group: root

- name: Locale-gen
  ansible.builtin.command: "arch-chroot /mnt locale-gen"
  register: set_locale_gen
  changed_when: set_locale_gen.rc > 0

- name: Set locale
  ansible.builtin.template:
    src: locale
    dest: /mnt/etc/locale.conf
    mode: '0644'
    owner: root
    group: root
