---

- name: Create config dirs
  ansible.builtin.file:
    dest: "/usr/local/etc/{{ etc_dirs }}"
    state: directory
    mode: '0750'
    owner: "{{ admin_user }}"
    group: users
  loop:
    - builds
    - user_configs
    - scripts
  loop_control:
    loop_var: etc_dirs
  become: true
